# Generated by Django 4.1.3 on 2022-11-01 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_organizer', '0003_group_course_alter_course_curator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='class_organizer.group', verbose_name='Группа'),
        ),
    ]
