# Generated by Django 4.1.3 on 2022-11-02 13:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_organizer', '0004_alter_student_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='class_organizer.curator', verbose_name='Куратор'),
        ),
    ]
