# Generated by Django 4.1.3 on 2022-11-02 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('class_organizer', '0005_alter_course_curator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='curator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='class_organizer.curator', verbose_name='Куратор'),
        ),
        migrations.AlterField(
            model_name='group',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='class_organizer.course', verbose_name='Направление'),
        ),
    ]
