# Generated by Django 4.1.3 on 2022-11-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('class_organizer', '0007_remove_group_subjects_course_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.AddField(
            model_name='student',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='ФИО'),
            preserve_default=False,
        ),
    ]
